
#ALL_MODULES :=

#INCLUDE_CMD     = $(MODULE_CMD)
#INCLUDE_TEST    = $(MODULE_TEST)
#INCLUDE_LIB     = $(MODULE_LIB)
#INCLUDE_LIB_INT = $(MODULE_LIB)/interface

#MODULE_CMD_DEPS  = $(INCLUDE_CMD)  $(INCLUDE_LIB_INT)
#MODULE_TEST_DEPS = $(INCLUDE_TEST) $(INCLUDE_LIB_INT)
#MODULE_LIB_DEPS  = $(INCLUDE_LIB)  $(INCLUDE_LIB_INT)

ARRAY := $(ONE) $(TWO) $(THREE)

ARRAY_I := $(foreach i,$(ARRAY),-I$(i))

$(info ARRAY=$(ARRAY))
$(info ARRAY_I=$(ARRAY_I))
