ifndef TOPLEVELWD
include $(dir $(lastword $(MAKEFILE_LIST)))../makefile
.DEFAULT_GOAL := $(DEFAULT_GOAL_LIBRARY)
else

LOCATION_LIB_INT := $(relCWD)interface

LIB_INTERFACE := $(relCWD)interface

$(call enter,src)

endif
